Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-10, with the labels that each got.

#1741 Refactored Stripe currency unit multiplier logic
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#1785 Setting app info for Stripe API calls
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#627 BUG: Membership level id and name were missing from Billing Failure …
  services/stripe-webhook.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1768 Deprecate Stripe subscription updates
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Discussion, Type: Enhancement, Difficulty: Medium, Impact: High

#1800 Remove deprecated customer logic from Stripe webhook.
  services/stripe-webhook.php
Labels: Type: Refactor, Difficulty: Easy, Impact: Low, Status: Code Review

#1801 Adding deprecation notice to public static webhook methods in Stripe …
  classes/gateways/class.pmprogateway_stripe.php
  includes/functions.php
Labels: Type: Refactor, Difficulty: Easy, Impact: Low, Status: Code Review
