Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-06, with the labels that each got.

#1671 Remove query string from URI path to prevent "File not found" errors
  services/getfile.php
Labels: Status: Code Review

#1651 BUG FIX: Adjusted deprecated function
  js/pmpro-login.js
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Bug

#1653 Hide gateways passwords behind asterisks
  classes/gateways/class.pmprogateway_authorizenet.php
  classes/gateways/class.pmprogateway_braintree.php
  classes/gateways/class.pmprogateway_cybersource.php
  classes/gateways/class.pmprogateway_paypal.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_paypalstandard.php
  classes/gateways/class.pmprogateway_stripe.php
  classes/gateways/class.pmprogateway_twocheckout.php
  css/admin.css
Labels: Difficulty: Medium, Impact: Medium, Status: Code Review, Type: Enhancement

#1655 BUG: Missing return statement in deprecated function
  includes/deprecated.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Bug

#1656 BUG FIX: FIx warning in searches/pages when PMPro pages is not set.
  includes/content.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Bug

#1659 Fix warnings being generated when using PHP 8 and Divi
  includes/compatibility/divi.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Bug

#1664 Fixed non-prefixed function name
  includes/lib/stripe-apple-pay/stripe-apple-pay.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Bug, Type: Conflict

#1666 User registered date is now shown in local time.
  adminpages/dashboard.php
  adminpages/reports/login.php
  classes/class-pmpro-members-list-table.php
Labels: Difficulty: Easy, Impact: Medium, Status: Code Review, Type: Bug

#1675 Add new actions and add phpcdoc for hooks where possible
  adminpages/membershiplevels.php
  adminpages/orders.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Enhancement

#1676 Add a new action during checkout process, just before user auth
  preheaders/checkout.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Enhancement

#1663 i18n apply discount code
  services/applydiscountcode.php
Labels: Difficulty: Medium, Impact: Medium, Status: Code Review, Type: Bug

#1591 Always fire pmpro_update_order/pmpro_updated_order
  classes/class.memberorder.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, Type: Enhancement

#1679 Improve escaping for Apply Discount Code JS
  services/applydiscountcode.php
Labels: Difficulty: Medium, Impact: Medium, Status: Code Review, Type: Bug

#1680 Add CARDONFILE compatibility for Payflow Pro gateway
  classes/gateways/class.pmprogateway_payflowpro.php
Labels: Blocking Next Release, Difficulty: Medium, Impact: High, Status: Code Review, Type: Bug, Type: Enhancement
