Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-08, with the labels that each got.

#1712 Also checking for the .org version of Email Templates Admin Editor in deprecation script.
  includes/deprecated.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#1714 Establishing style for scrollable boxes throughout core plugin.
  adminpages/advancedsettings.php
  css/admin.css
  includes/profile.php
Labels: Type: Bug, Difficulty: Medium, Impact: Medium, Status: Code Review

#1720 Updating readme to include some 2.6+ features and other things not mentioned that are awesome.
  readme.txt
Labels: Difficulty: Easy, Impact: Low, Status: Code Review

#1732 Replace !empty() check with isset() for decimal option
  includes/functions.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1729 Fix PHP 8 fatal error that could occur in pmpro_email_templates_email_data
  includes/email.php
Labels: Type: Bug, Difficulty: Easy, Impact: Highest, Type: Conflict, Status: Code Review

#1719 Do not autoload email templates since we added that feature as default
  includes/email.php
  includes/functions.php
Labels: Type: Bug, Difficulty: Easy, Impact: Medium, Status: Code Review

#1730 Remove unused variable which generates PHP Warning
  includes/content.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1722 Added Email Templates as a link on dashboard for getting started.
  adminpages/dashboard.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#1724 Ensure our admin scripts/styles only load on our pages
  CHANGELOG.txt
  includes/scripts.php
  paid-memberships-pro.php
  readme.txt
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1686 Abstract admin actions and make them filterable for Discount Codes, Membership Levels, and Orders
  adminpages/discountcodes.php
  adminpages/membershiplevels.php
  adminpages/orders.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Low, Status: Code Review

#1735 Update Stripe connected status to consider legacy keys
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Medium, Impact: Medium, Status: Code Review

#1717 Site Health Data Implemented
  includes/site-health.php
  paid-memberships-pro.php
Labels: Type: Feature, Difficulty: Medium, Impact: Medium

#1745 Add information needed by the Blocks JS for levels
  blocks/blocks.php
Labels: Type: Bug, Difficulty: Easy, Impact: Medium, Status: Code Review

#1746 Fix/admin js
  adminpages/emailtemplates.php
  blocks/blocks.php
  includes/scripts.php
  js/pmpro-admin.js
Labels: Type: Bug, Difficulty: Easy, Impact: Medium, Type: Conflict, Status: Code Review
