Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-11, with the labels that each got.

#1833 Restore pmpro_cancelMembershipLevel() function call for recurring_pay…
  services/ipnhandler.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1837 Add Constant Info to Site Health
  classes/class-pmpro-site-health.php
Labels: Type: Support, Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1830 Added function pmpro_send_200_http_response()
  includes/functions.php
  services/stripe-webhook.php
Labels: Type: Bug, Difficulty: Easy, ✓ Ready for Merge

#1829 Update minimum PHP version in readme.txt so that it's exposed to WordPress.org
  readme.txt
Labels: Type: Support, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1817 Now including time when calculating profile start date.
  classes/gateways/class.pmprogateway.php
  classes/gateways/class.pmprogateway_authorizenet.php
  classes/gateways/class.pmprogateway_braintree.php
  classes/gateways/class.pmprogateway_check.php
  classes/gateways/class.pmprogateway_cybersource.php
  classes/gateways/class.pmprogateway_payflowpro.php
  classes/gateways/class.pmprogateway_paypal.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_stripe.php
  includes/functions.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#1827 Add .htaccess checks to Site Health
  classes/class-pmpro-site-health.php
Labels: Type: Support, Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1815 Allow users to view and delete existing subscription updates for users.
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review

#1822 Add WP.com compatibiltiy for Jetpack SSO
  includes/compatibility.php
  includes/compatibility/wp-com.php
Labels: Type: Bug, Difficulty: Medium, Impact: Medium, Type: Conflict, ✓ Ready for Merge

#1849 Ensuring that we have a server protocol
  includes/functions.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1857 Update plugin version and add changelog
  paid-memberships-pro.php
  readme.txt
Labels: ✓ Ready for Merge

#1861 Fix PHP notice issues in name parser library
  includes/lib/name-parser.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1860 Add option to remove duplicate levels after memberhsip level change.
  includes/functions.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1862 Cleaned up REST API For Zapier
  includes/rest-api.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge
