Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-07, with the labels that each got.

#1684 BUG FIX: Fix explode parameters
  services/getfile.php
Labels: Difficulty: Easy, Impact: Medium, Status: Code Review, Type: Bug

#1668 Zapier native integration - update to REST API.
  includes/rest-api.php
Labels: Difficulty: Medium, Impact: Low, Status: Code Review, Type: Enhancement

#1697 Add Generate Translations manual workflow action
  .github/workflows/generate-translations.yml
Labels: Difficulty: Easy, Impact: Low, Type: Localization

#1699 Remove extra pot files
  languages/paid-memberships-pro-es_CL.pot
  languages/paid-memberships-pro-es_ES.pot
  languages/paid-memberships-pro-es_PE.pot
Labels: Difficulty: Easy, Impact: Low
