Repository strangerstudios/paid-memberships-pro, pull requests merged in 2021-09, with the labels that each got.

#1705 Add initial codeception testing
  .env
  .env.example
  .env.testing.tric
  .gitattributes
  .github/workflows/tests-php.yml
  .gitignore
  codeception.dist.yml
  codeception.example.yml
  codeception.tric.yml
  composer.json
  includes/functions.php
  tests/TESTS.md
  tests/_bootstrap.php
  tests/_data/dump.sql
  tests/_helpers/traits/trait-utility.php
  tests/_support/Factories/PMPro_LevelFactory.php
  tests/_support/Helper/Integration.php
  tests/_support/Helper/Restv1.php
  tests/_support/Helper/Wpunit.php
  tests/_support/TestCases/TestCase.php
  tests/_support/WpunitTester.php
  tests/_support/_generated/WpunitTesterActions.php
  tests/bootstrap.php
  tests/includes/test-functions.php
  tests/to-migrate/_helpers/factory/class-checkout-factory.php
  tests/to-migrate/_helpers/factory/class-level-factory.php
  tests/to-migrate/_helpers/factory/class-level.php
  tests/to-migrate/_helpers/factory/class-order-factory.php
  tests/to-migrate/_helpers/factory/tests/test-checkout-factory.php
  tests/to-migrate/_helpers/factory/tests/test-order-factory.php
  tests/to-migrate/_helpers/helpers.php
  tests/to-migrate/classes/gateways/no-test-classes.pmprogateway_stripe.php
  tests/wpunit.suite.dist.yml
  tests/wpunit/_bootstrap.php
  tests/wpunit/functions/Levels/ChangeMembershipLevelTest.php
  tests/wpunit/functions/Levels/GetAllLevelsTest.php
  tests/wpunit/functions/Levels/GetLevelTest.php
  tests/wpunit/functions/Levels/GetMembershipLevelsForUserTest.php
  tests/wpunit/functions/Levels/HasMembershipLevelTest.php
  tests/wpunit/functions/SessionTest.php
Labels: Type: Feature, Difficulty: Hard, Impact: Low, Status: Code Review

#1749 Check $pagenow for admin-post.php on whether to block dashboard
  includes/admin.php
Labels: Difficulty: Easy, Impact: Medium, Type: Conflict, Status: Code Review

#1753 Dashboard widget body colspan match head number of columns
  adminpages/dashboard.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1743 Site Health Data Implemented
  classes/class-pmpro-site-health.php
  includes/admin.php
  paid-memberships-pro.php
Labels: Type: Feature, Difficulty: Medium, Impact: Medium, Status: Code Review

#1760 Admin page: orders.php > Remove trailing space
  adminpages/orders.php
Labels: Type: Bug

#1758 Don't access $_REQUEST for already parsed params
  adminpages/discountcodes.php
Labels: Type: Bug

#1757 Define missing local and global variables
  adminpages/discountcodes.php
Labels: Type: Bug

#1755 Use admin_url(...) instead of get_admin_url(null,...)
  adminpages/admin_header.php
  adminpages/discountcodes.php
  adminpages/membershiplevels.php
  adminpages/orders.php
  adminpages/reports/login.php
  includes/adminpages.php
  preheaders/checkout.php
Labels: Type: Bug

#1762 ENHANCEMENT: Only update user meta that is passed through.
  preheaders/checkout.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1765 Separated template setting logic from data setting logic. Helps if th…
  classes/class.pmproemail.php
Labels: Type: Bug, Difficulty: Medium, Impact: Low, Status: Code Review

#1770 Expand allowed HTML tags for pmpro_kses and add a way to stop normal processing
  includes/email.php
  includes/functions.php
  tests/_data/kses/email-allowed.html
  tests/_data/kses/email-disallowed.html
  tests/_support/_generated/WpunitTesterActions.php
  tests/wpunit/functions/KsesTest.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Low, Status: Code Review

#1742 Document pmpro-stripe.js
  js/pmpro-stripe.js
Labels: Type: Support, Difficulty: Easy, Impact: Low, Status: Code Review

#1783 add missing email var
  adminpages/emailtemplates.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1784 Add link to show Stripe legacy API settings.
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Medium
