Repository strangerstudios/paid-memberships-pro, pull requests merged in 2022-01, with the labels that each got.

#1879 Current screen name gets partially translated
  classes/class-pmpro-members-list-table.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1866 Pagesetting post type
  adminpages/pagesettings.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1891 Some MySQL setups require a primary key for each table. Going to doub…
  includes/setup.sql
  includes/upgradecheck.php
Labels: Blocking Next Release

#1894 Use wp_strip_all_tags to remove contents of script/style tags
  includes/content.php
Labels: Type: Bug, Difficulty: Medium, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1898 Update to force Site Health to report on all levels, including hidden.
  classes/class-pmpro-site-health.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1781 Change status to receive new membership information
  includes/rest-api.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1899 Fix PHP 8 fatal error in `services/authnet-silent-post.php`.
  services/authnet-silent-post.php
Labels: Type: Bug, Difficulty: Easy, Impact: High, Status: Code Review, ✓ Ready for Merge

#1878 Recaptcha free levels
  adminpages/advancedsettings.php
  pages/checkout.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1900 Replaced use of deprecated method set_customer()
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Easy, Impact: High, Status: Code Review, ✓ Ready for Merge

#1905 Making sure to calculate Stripe unit amount based on selected currenc…
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Easy, Impact: Medium, Status: Code Review, ✓ Ready for Merge

#1904 Changelog + version updates
  adminpages/pagesettings.php
  classes/gateways/class.pmprogateway_stripe.php
  includes/upgradecheck.php
  paid-memberships-pro.php
  readme.txt
  services/stripe-webhook.php
Labels: Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1912 Fixed issue where trial period days can be calculated incorrectly for Stripe subscriptions
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Easy, Impact: High, ✓ Ready for Merge

#1915 BUG FIX: Fix fatal error for older PHP sites when visiting the page settings in admin dashboard.
  adminpages/pagesettings.php
Labels: Type: Bug, Difficulty: Easy, Impact: High, Status: Code Review, ✓ Ready for Merge

#1895 Better support custom field types with new hooks
  classes/class-pmpro-field.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1896 Better escape custom HTML attributes in field rendering and add new hook to customize them before render
  classes/class-pmpro-field.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review, ✓ Ready for Merge

#1858 Implementing setter for PMPro_Subscription class
  classes/class-pmpro-subscription.php
  classes/class.memberorder.php
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Enhancement, Type: Refactor, Difficulty: Easy, ✓ Ready for Merge

#1916 Fixing issue where billing address not added to Stripe customer
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, ✓ Ready for Merge
