Repository strangerstudios/paid-memberships-pro, pull requests merged in 2022-03, with the labels that each got.

#1981 Enhancement/colon search
  adminpages/memberslist-csv.php
  classes/class-pmpro-members-list-table.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1929 When passing amounts to gateways, pass as a string with precision issues addressed
  classes/gateways/class.pmprogateway_authorizenet.php
  classes/gateways/class.pmprogateway_braintree.php
  classes/gateways/class.pmprogateway_cybersource.php
  classes/gateways/class.pmprogateway_payflowpro.php
  classes/gateways/class.pmprogateway_paypal.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_paypalstandard.php
  classes/gateways/class.pmprogateway_stripe.php
  classes/gateways/class.pmprogateway_twocheckout.php
  includes/functions.php
  includes/init.php
  tests/wpunit/functions/PriceTest.php
Labels: Type: Bug, Difficulty: Hard, Impact: High, Status: Needs Code

#1987 Fix typo in settings
  adminpages/advancedsettings.php
Labels: ✓ Ready for Merge

#1991 Add .pmpro_admin to the path for certain un-prefixed classes
  js/pmpro-admin.js
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Type: Conflict, ✓ Ready for Merge

#1992 New filter to perform actions using http post request's response
  classes/gateways/class.pmprogateway_paypal.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_paypalstandard.php
Labels: ✓ Ready for Merge

#1996 Add filters to change gateway ipn/webhook logfile
  services/authnet-silent-post.php
  services/braintree-webhook.php
  services/stripe-webhook.php
  services/twocheckout-ins.php
Labels: ✓ Ready for Merge

#1976 i18n + escape codebase revision 2022-02
  adminpages/addons.php
  adminpages/admin_header.php
  adminpages/advancedsettings.php
  adminpages/dashboard.php
  adminpages/discountcodes.php
  adminpages/emailsettings.php
  adminpages/functions.php
  adminpages/license.php
  adminpages/membershiplevels.php
  adminpages/orders.php
  adminpages/pagesettings.php
  adminpages/paymentsettings.php
  adminpages/reports/login.php
  adminpages/reports/memberships.php
  adminpages/reports/sales.php
  adminpages/templates/orders-email.php
  adminpages/templates/orders-print.php
  adminpages/updates.php
  classes/class-pmpro-admin-activity-email.php
  classes/class-pmpro-members-list-table.php
  classes/gateways/class.pmprogateway_authorizenet.php
  classes/gateways/class.pmprogateway_braintree.php
  classes/gateways/class.pmprogateway_check.php
  classes/gateways/class.pmprogateway_cybersource.php
  classes/gateways/class.pmprogateway_payflowpro.php
  classes/gateways/class.pmprogateway_paypal.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_paypalstandard.php
  classes/gateways/class.pmprogateway_stripe.php
  classes/gateways/class.pmprogateway_twocheckout.php
  includes/lib/Twocheckout/Twocheckout/TwocheckoutCharge.php
  includes/license.php
  includes/login.php
  includes/menus.php
  includes/metaboxes.php
  includes/notifications.php
  includes/profile.php
  includes/updates.php
  includes/updates/upgrade_1_9_4.php
  pages/billing.php
  pages/cancel.php
  pages/checkout.php
  pages/confirmation.php
  pages/invoice.php
  pages/levels.php
  services/applydiscountcode.php
  shortcodes/pmpro_account.php
Labels: Type: Bug, Difficulty: Medium, Impact: Medium, ✓ Ready for Merge

#2001 Fix/improve various PHPDocs in `includes/functions.php`.
  includes/functions.php
Labels: ✓ Ready for Merge

#2006 Add filter for BrainTree transactions to allow additional data to be passed to BrainTree.
  classes/gateways/class.pmprogateway_braintree.php
Labels: ✓ Ready for Merge
