Repository strangerstudios/paid-memberships-pro, pull requests merged in 2022-02, with the labels that each got.

#1943 Move bootstrap setting to the top level to match new location
  codeception.dist.yml
  tests/_data/dump-acceptance.sql
  tests/_data/dump.sql
Labels: Type: Bug, Difficulty: Medium, Impact: Medium

#1957 Feature/license updates
  adminpages/addons.php
  classes/gateways/class.pmprogateway_stripe.php
  includes/addons.php
  includes/license.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1942 Fixing update function for PayPal Website Payments
  classes/gateways/class.pmprogateway_paypal.php
Labels: Type: Bug, Difficulty: Easy, Impact: Medium, ✓ Ready for Merge

#1908 Add pmpro_webhook_unhandled action at the end of any webhook
  includes/functions.php
  services/braintree-webhook.php
  services/ipnhandler.php
  services/stripe-webhook.php
  services/twocheckout-ins.php
Labels: Difficulty: Easy, Impact: Low, Type: Customization, ✓ Ready for Merge

#1934 fixed misspelling in text domain of __() function in pmpro_reset_pass…
  includes/login.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1919 Remove unused condition on sending mail
  classes/class.pmproemail.php
Labels: Type: Refactor, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1936 Add out text domain where missing and not covered by wp global text domain
  adminpages/advancedsettings.php
  adminpages/license.php
  adminpages/orders.php
  adminpages/updates.php
  blocks/login/inspector.js
  classes/class-pmpro-admin-activity-email.php
  classes/gateways/class.pmprogateway_twocheckout.php
  includes/lib/SendWP/sendwp.php
  includes/login.php
  includes/privacy.php
  js/blocks.build.js
Labels: Type: Bug, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1940 Better error handling when Stripe Price not found
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Medium, Impact: Low, Status: Code Review

#1928 Fixed error when getting Stripe customer for user and other cleanup
  classes/gateways/class.pmprogateway_stripe.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, ✓ Ready for Merge

#1953 WPCS on cleanup.php file
  includes/cleanup.php
Labels: Type: Bug, Difficulty: Easy, Impact: Low, Status: Code Review

#1925 REST API Changes for Zapier Updates.
  includes/rest-api.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Low, ✓ Ready for Merge

#1767 Handle some well known txn_type to avoid misleading ipn logs
  services/ipnhandler.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Low, ✓ Ready for Merge

#1911 Improved tooltips and styling for the new vs renewal revenue report.
  adminpages/reports.php
  adminpages/reports/sales.php
  css/admin.css
  includes/functions.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Medium
