Repository strangerstudios/paid-memberships-pro, pull requests merged in 2022-04, with the labels that each got.

#1759 Order's deletion message similar to discount's deletion message
  adminpages/orders.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Low, Status: Needs Thought

#1948 Refunds for Stripe & PayPal Express
  adminpages/orders.php
  classes/class.pmproemail.php
  classes/gateways/class.pmprogateway_paypalexpress.php
  classes/gateways/class.pmprogateway_stripe.php
  includes/email-templates.php
  includes/functions.php
  includes/profile.php
  services/ipnhandler.php
  services/stripe-webhook.php
Labels: Type: Enhancement, Difficulty: Medium, Impact: Medium, Status: Code Review

#1999 Add cron helper functions and implement filter to hook into to register Stripe sub cron
  classes/class-pmpro-site-health.php
  classes/gateways/class.pmprogateway_stripe.php
  includes/crons.php
  includes/functions.php
  includes/license.php
  includes/updates/upgrade_1_8_7.php
  includes/updates/upgrade_2_6.php
  includes/upgradecheck.php
  paid-memberships-pro.php
Labels: Type: Bug, Type: Enhancement, Difficulty: Medium, Impact: Medium, Status: Code Review

#2020 Add membership_id to REST API response for recent orders.
  includes/rest-api.php
Labels: Type: Enhancement, Difficulty: Easy, Impact: Medium, ✓ Ready for Merge
