Repository strangerstudios/paid-memberships-pro, pull requests merged in 2022-11, with the labels that each got.

#2245 Change message on membership level save ("updated")
  adminpages/membershiplevels.php
Labels: Blocking Next Release

#2246 Add more allowed HTML for field descriptions
  adminpages/advancedsettings.php
Labels: Blocking Next Release

#2251 Stripe Checkout now saves uploaded files
  classes/gateways/class.pmprogateway_stripe.php
  services/stripe-webhook.php
Labels: Blocking Next Release

#2262 Fixed attribute setting for Require membership block.
  blocks/membership/block.js
Labels: Blocking Next Release

#2263 Added !!levels_url!!, docblocks and minor WPCS to sections of the email class.
  classes/class.pmproemail.php
Labels: Blocking Next Release

#2270 Fixing issue where fields may not show on profile
  includes/fields.php
Labels: Blocking Next Release

#2252 Fixing col name for membership_id in get_orders()
  classes/class.memberorder.php
Labels: Blocking Next Release

#2273 Fix reference to the user id
  services/stripe-webhook.php
Labels: Blocking Next Release

#2274 required asterisk now appears before the hint paragraph if found
  js/pmpro-checkout.js
Labels: Blocking Next Release

#2275 Fix reference to the billing zipcode's user meta
  classes/class.memberorder.php
Labels: Blocking Next Release

#2272 Adding fallbacks when finding billing addresses
  services/stripe-webhook.php
Labels: Blocking Next Release

#2254 Add content restriction settings to Elementor containers
  includes/compatibility/elementor/class-pmpro-elementor-content-restriction.php
  includes/compatibility/elementor/class-pmpro-elementor.php
Labels: ✓ Ready for Merge

#2277 Fix trial wording for non $0 custom trials.
  includes/functions.php
Labels: ✓ Ready for Merge

#2284 Add id attribute to hidden bcountry field
  pages/checkout.php
Labels: Blocking Next Release, ✓ Ready for Merge

#2285 Add compatibility for Avada Theme
  includes/compatibility.php
  includes/compatibility/avada.php
Labels: ✓ Ready for Merge

#2289 Adding IDs to billing address fields to avoid Stripe errors
  pages/billing.php
  pages/checkout.php
Labels: Blocking Next Release

#2290 Avoiding sprintf issues during cron runs
  scheduled/crons.php
Labels: Blocking Next Release

#2280 Fix Authorize.net sites using profile start date filter
  classes/gateways/class.pmprogateway_authorizenet.php
Labels: Blocking Next Release
